In [145]:
from main import main

main()

Función lógica AND
Pesos: w1=0.3352993131200776 w2=0.06242816355855646
Función lógica XOR
Pesos: w1=0.38983224125783533 w2=0.5577189108631895


In [4]:
import numpy as np
datos = np.genfromtxt('TP3-ej2-conjunto.csv', delimiter=",")
datos

array([[   nan,    nan,    nan,    nan],
       [ 1.2  , -0.8  ,  0.   , 21.755],
       [ 1.2  ,  0.   , -0.8  ,  7.176],
       [ 1.2  , -0.8  ,  1.   , 43.045],
       [ 0.   ,  1.2  , -0.8  ,  2.875],
       [ 7.9  ,  1.   ,  0.   , 26.503],
       [ 0.4  ,  0.   ,  2.7  , 68.568],
       [ 0.   ,  0.4  ,  2.7  , 61.301],
       [-1.3  ,  3.23 ,  3.   , 23.183],
       [ 0.4  ,  2.7  ,  0.   ,  2.82 ],
       [ 0.4  ,  2.7  ,  2.   , 17.654],
       [-1.3  ,  0.   ,  3.23 , 72.512],
       [ 0.   , -1.3  ,  3.23 , 88.184],
       [ 7.9  ,  1.   , -2.   ,  4.653],
       [ 1.8  ,  0.   ,  1.6  , 49.   ],
       [ 0.   , -2.   ,  2.   , 76.852],
       [-0.5  ,  0.6  ,  0.   ,  7.871],
       [ 0.   ,  1.8  ,  1.6  , 18.543],
       [-2.   ,  2.   ,  0.   ,  2.66 ],
       [-0.5  ,  0.6  ,  2.5  , 51.   ],
       [ 7.9  ,  0.   ,  1.   , 64.107],
       [-1.3  ,  3.23 ,  0.   ,  1.48 ],
       [ 0.   ,  7.9  ,  1.   ,  0.32 ],
       [-2.   ,  0.   ,  2.   , 40.131],
       [-2.   , 

In [159]:
import numpy as np

def compute_error_step(x, y, w):

    error = 0
    for u in range(x.shape[0]):
        z = 0
        for i in range(x.shape[1]):
            z = z + w[i] * x[u, i] 
        y_pred = 1 if z >= 0 else 0      # Activador escalon
        error += (y_pred - y[u])**2

    return error / len(x)


import sys
import numpy as np
import random
import pandas as pd

# Ruta del archivo CSV
archivo_csv = "TP3-ej2-conjunto.csv"
# Leer datos CSV en un DataFrame de pandas
datos_df = pd.read_csv(archivo_csv)
# Convertir DataFrame a un array de NumPy
datos_array = datos_df.to_numpy()
# Extract feature columns (x1, x2, x3) into 'x' array
x = datos_array[:, :-1]  # Assuming 'y' is the last column

# Extract target column (y) into 'y' array
y = datos_array[:, -1]

eta = 0.1
epoch = 100   

def perceptron_simple_step(x, y, eta, epoch):
    # Inicializar los pesos aleatoriamente
    w = np.array([random.random() for i in range(x.shape[1])]) 
    w_new = np.zeros_like(w, dtype=np.float32)

    error = 0       
    min_error = sys.maxsize 
    w_min = np.zeros_like(w, dtype=np.float32)   

    for u in range(len(x)):
        c = 0           # corrida
        while (min_error > 0) and (c < epoch):
            # Calcular la salida bruta
            z=0
            for i in range(x.shape[1]):
                z = z + w[i] * x[u, i] 

            # Aplicar la función de activación escalón
            y_pred = 1 if z >= 0 else 0

            # Actualizar los pesos
            for j in range(x.shape[1]):
                w_new[j] = w[j] + eta * (y[u] - y_pred) * x[u, j]
                # Actualizar los pesos
                w[j] = w_new[j]

            error = compute_error_step(x, y, w)
            if error < min_error:
                min_error = error
                w_min = w

            c += 1
    return w_min

perceptron_simple_step(x,y,eta,epoch)

array([ 7409.84863281,  -327.92211914, 15557.765625  ])

In [24]:
import numpy as np
import random

alpha = 0.1
x = np.array([[1, 2], [3, 4]])
y = np.array([-1, -1, -1, 1])
w = np.array([1, 1])
w_new = np.array(x.shape[1]) 

w_new

array(2)

In [43]:
for i in range(2):
        print(i)

0
1


In [46]:
x = np.array([[1, 1], [4, 5]])

for i in range(x.shape[1]):
        print(i)

0
1


In [94]:
import pandas as pd

# Ruta del archivo CSV
archivo_csv = "TP3-ej2-conjunto.csv"

# Leer datos CSV en un DataFrame de pandas
datos_df = pd.read_csv(archivo_csv)

# Convertir DataFrame a un array de NumPy
datos_array = datos_df.to_numpy()

datos_array

array([[ 1.2  , -0.8  ,  0.   , 21.755],
       [ 1.2  ,  0.   , -0.8  ,  7.176],
       [ 1.2  , -0.8  ,  1.   , 43.045],
       [ 0.   ,  1.2  , -0.8  ,  2.875],
       [ 7.9  ,  1.   ,  0.   , 26.503],
       [ 0.4  ,  0.   ,  2.7  , 68.568],
       [ 0.   ,  0.4  ,  2.7  , 61.301],
       [-1.3  ,  3.23 ,  3.   , 23.183],
       [ 0.4  ,  2.7  ,  0.   ,  2.82 ],
       [ 0.4  ,  2.7  ,  2.   , 17.654],
       [-1.3  ,  0.   ,  3.23 , 72.512],
       [ 0.   , -1.3  ,  3.23 , 88.184],
       [ 7.9  ,  1.   , -2.   ,  4.653],
       [ 1.8  ,  0.   ,  1.6  , 49.   ],
       [ 0.   , -2.   ,  2.   , 76.852],
       [-0.5  ,  0.6  ,  0.   ,  7.871],
       [ 0.   ,  1.8  ,  1.6  , 18.543],
       [-2.   ,  2.   ,  0.   ,  2.66 ],
       [-0.5  ,  0.6  ,  2.5  , 51.   ],
       [ 7.9  ,  0.   ,  1.   , 64.107],
       [-1.3  ,  3.23 ,  0.   ,  1.48 ],
       [ 0.   ,  7.9  ,  1.   ,  0.32 ],
       [-2.   ,  0.   ,  2.   , 40.131],
       [-2.   ,  2.   , -1.   ,  0.995],
       [ 0.   , 

In [114]:
import numpy as np
import random
import pandas as pd

# Ruta del archivo CSV
archivo_csv = "TP3-ej2-conjunto.csv"
# Leer datos CSV en un DataFrame de pandas
datos_df = pd.read_csv(archivo_csv)
# Convertir DataFrame a un array de NumPy
datos_array = datos_df.to_numpy()
# Extract feature columns (x1, x2, x3) into 'x' array
x = datos_array[:, :-1]  # Assuming 'y' is the last column

# Extract target column (y) into 'y' array
y = datos_array[:, -1]

w = np.array([random.random() for i in range(x.shape[1])]) 
w_new = np.zeros_like(w, dtype=np.float32)



(3,)

In [151]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([-1, 1])
w = np.array([1, 1])


error = 0
y_pred = np.zeros_like(w, dtype=np.float32)
for u in range(x.shape[0]):
    z=0
    for i in range(x.shape[1]):
        z = z + w[i] * x[u, i] 
    y_pred[u] = 1 if z >= 0 else 0
    print(y_pred[u])
    error += (y_pred[u] - y[u])**2

e = error / len(x)

print(e)


1.0
1.0
2.0
